packaging_format = 2

id = "samba"
name = "Samba"
description.en = "Share directories on your private network thanks to SMB protocol"
description.fr = "Partager des dossiers sur un réseau privé via le protocole SMB"

version = "4.13.13~ynh1"

maintainers = ["Galette"]

[upstream]
license = "AGPL-3.0-only"
website = "https://www.samba.org/"
admindoc = "https://www.samba.org/samba/docs/"
code = "https://git.samba.org/?p=samba.git;a=summary"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

    [install.warning]
    ask.en = "I understand this app is only for private network purpose and i should not install it on a server with a public IP or open the 445 port on my home router."
    ask.fr = "Je comprends que cette application est uniquement à des fins de réseau privé et que je ne dois pas l'installer sur un serveur avec une adresse IP publique ou ouvrir le port 445 sur mon routeur."
    type = "display_text"

[resources]
    [resources.system_user]

    [resources.install_dir]
    dir = ["/etc/samba"]

    [resources.ports]
    main.default = 445
    main.exposed = "Both"

    [resources.data_dir]
    subdirs = ["share"]

    [resources.permissions]
    share.url = "/"
    share.show_tile = false
    share.allowed = "all_users"

    [resources.apt]
    packages = ["samba"]